In [4]:
#importing lib
import numpy as np

In [24]:
seq1='mimo'
seq2='mimo'


In [25]:
# size of matrix
size_x=len(seq1)+1
size_y=len(seq2)+1
# Creating a matrix with all zeros
matrix=np.zeros((size_x,size_y))
matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
# filling the first column of the matrix with the index of chracters from first string
for x in range(size_x):
  matrix[x,0]=x
for y in range(size_y):
  matrix[0,y]=y
matrix

array([[0., 1., 2., 3., 4.],
       [1., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0.],
       [3., 0., 0., 0., 0.],
       [4., 0., 0., 0., 0.]])

In [27]:
#for each column
for x in range(1,size_x):
  for y in range(1,size_y):
    if seq1[x-1]==seq2[y-1]:
      matrix[x,y]=min(
          matrix[x-1,y],
          matrix[x-1,y-1]+1,
          matrix[x,y-1]+1
      )
    else:
      matrix[x,y]=min(
          matrix[x-1,y]+1,
          matrix[x-1,y-1]+1,
          matrix[x,y-1]+1
      )


In [28]:
matrix

array([[0., 1., 2., 3., 4.],
       [1., 1., 2., 3., 4.],
       [2., 2., 2., 3., 4.],
       [3., 2., 3., 3., 4.],
       [4., 3., 3., 4., 4.]])